feat: upgrade logger to central-services-logger
mojaloop/mojaloop-simulator pull request #148
Opened 2022-11-02 00:39 UTC by kleyow

2022-11-15 15:03 UTC, kleyow commented on src/index.js
> -        Transports.sqlite(process.env.SQLITE_LOG_FILE),
Is it important to log to sqlite? Do we do this anywhere else?

2022-11-17 16:42 UTC, mdebarros requested changes
LGTM, just a minor suggestion change.

Let me know if you agree.

2022-11-17 16:42 UTC, mdebarros commented on src/index.js
> +    const simLogger = Logger;
```suggestion
    const simLogger = Logger.child({
            context: {
                app: 'simulator'
            }
        });
```

2022-11-17 16:42 UTC, mdebarros commented on src/index.js
> +    const reportLogger =  Logger;
```suggestion
    const reportLogger =  Logger.child({
            context: {
                app: 'report'
            }
        });
```

2022-11-17 16:42 UTC, mdebarros commented on src/index.js
> +    const testApiLogger =  Logger;
```suggestion
    const testApiLogger =  Logger.child({
            context: {
                app: 'test-api'
            }
        });
```

2022-11-17 17:13 UTC, mdebarros approved these changes, later dismissed

2022-11-17 18:25 UTC, elnyry-sam-k approved these changes

2022-11-17 18:26 UTC, merged