Feature transfers without quotes
mojaloop/mojaloop-simulator pull request #17
Opened 2019-11-22 14:47 UTC by vijayg10

To enable sending transfers to scheme adapter without previous party lookup and quote request, had to remove some required fields in mojaloop-simulator incoming transfer request.

2019-11-22 15:47 UTC, millerabel commented
Is this feature for perf testing?

-- Miller


> On Nov 22, 2019, at 5:48 PM, vijayg10 <notifications@github.com> wrote:
> 

﻿
To enable sending transfers to scheme adapter without previous party lookup and quote request, had to remove some required fields in mojaloop-simulator incoming transfer request.

You can view, comment on, or merge this pull request online at:

  https://github.com/mojaloop/mojaloop-simulator/pull/17

Commit Summary

Removed some required fields in transferRequest
Added build-perf in circleci yml file
File Changes

M .circleci/config.yml (36)
M src/simulator/api.yaml (5)
Patch Links:

https://github.com/mojaloop/mojaloop-simulator/pull/17.patch
https://github.com/mojaloop/mojaloop-simulator/pull/17.diff
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2019-11-22 19:00 UTC, vijayg10 commented
Yes Miller, this is for perf testing.

2019-11-22 19:42 UTC, elnyry commented
@millerabel Yes - for perf testing only, so that we can baseline, because, thats what we did earlier during the PI4 (end of phase3) effort (so that we can compare apples to apples).

2019-11-22 19:44 UTC, millerabel commented
I recall, yes, and makes sense. Thanks both!

Sent from my iPad

> On Nov 22, 2019, at 10:42 PM, Sam <notifications@github.com> wrote:
> 

﻿
@millerabel Yes - for perf testing only, so that we can baseline, because, thats what we did earlier during the PI4 (end of phase3) effort (so that we can compare apples to apples).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2019-11-25 18:48 UTC, mdebarros approved these changes
+1

2019-11-25 18:48 UTC, mdebarros commented on .circleci/config.yml
> +# Removed this because we are getting the following error in PR build process
I think you did not include the error or the explanation as to why this was commented out?

2019-11-25 18:49 UTC, mdebarros requested changes
Have a look at  my comment.

2019-11-25 19:48 UTC, mdebarros approved these changes
+1

2019-11-25 20:29 UTC, merged