working chart
mojaloop/mojaloop-simulator pull request #24
Opened 2019-12-11 13:13 UTC by shashi165

2019-12-11 14:35 UTC, partiallyordered submitted a review, later dismissed

2019-12-18 19:00 UTC, partiallyordered requested changes

2019-12-18 19:00 UTC, msk- commented on helm/values.yaml
> +      RULES_FILE: ./rules.json
This appears unused. But we should use it, as I believe users will want to configure rules.

2019-12-19 14:13 UTC, partiallyordered approved these changes

2019-12-19 14:15 UTC, msk- commented on helm/values.yaml
> +      RULES_FILE: ./rules.json
Actually, I now realise this is the location inside the container where the rules are expected to be. This should probably read more like
```suggestion
      RULES_FILE: /rules.json
```

2019-12-19 16:26 UTC, partiallyordered approved these changes

2019-12-19 16:27 UTC, elnyry-sam-k approved these changes

2019-12-19 16:27 UTC, merged